build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  armv7: ghcr.io/home-assistant/armv7:3.16
  amd64: ghcr.io/home-assistant/amd64:3.16
  i386: ghcr.io/home-assistant/i386:3.16
  armhf: ghcr.io/home-assistant/armhf:3.16