---
name: InfluxDB2
version: "1.0.1"
slug: influxdb2
description: Scalable datastore for metrics, events, and real-time analytics
url: https://github.com/kapwebdr/hassio-addons-repo/tree/master/influxdb2
codenotary: damien@kapweb.com
startup: services
homeassistant: 0.92.0b2
hassio_api: true
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
map:
  - share:rw
ports:
  8086/tcp: 8086
ports_description:
  8086/tcp: InfluxDB server
auth_api: true
options:
  envvars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  envvars:
    - name: match(^INFLUXDB_([A-Z0-9_])+$)
      value: str
